import { SugarElement } from 'ssephox/sugar/api/node/SugarElement';
declare const container: SugarElement<HTMLDivElement>;
declare const d1: SugarElement<HTMLDivElement>;
declare const p1: SugarElement<HTMLParagraphElement>;
declare const p2: SugarElement<HTMLParagraphElement>;
declare const p3: SugarElement<HTMLParagraphElement>;
declare const s1: SugarElement<HTMLSpanElement>;
declare const s2: SugarElement<HTMLSpanElement>;
declare const s3: SugarElement<HTMLSpanElement>;
declare const s4: SugarElement<HTMLSpanElement>;
declare const t1: SugarElement<Text>;
declare const t2: SugarElement<Text>;
declare const t3: SugarElement<Text>;
declare const t4: SugarElement<Text>;
declare const t5: SugarElement<Text>;
declare const t6: SugarElement<Text>;
declare const t7: SugarElement<Text>;
declare const ul: SugarElement<HTMLUListElement>;
declare const li: SugarElement<HTMLLIElement>;
declare const connect: () => void;
export { container, d1, p1, p2, p3, s1, s2, s3, s4, t1, t2, t3, t4, t5, t6, t7, ul, li, connect };
//# sourceMappingURL=TestPage.d.ts.map